import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer.js";
import Header from "../../components/header";
//import Session from "./sessionProvider";
import Provider from "./provider";
//import { SessionProvider } from "next-auth/react";
//import { auth } from "./api/auth/[...nextauth]/options";
import "./font.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Community Goal giver",
  description: "Generated by Community Goal Giver Team",
};

export default async function RootLayout({ children }) {
  //const session = await auth();
  return (
      <html lang="en">
        <body className={inter.className}>
          <Provider>
            <Header />
            <main>{children}</main>
            <div className="sticky bottom-0 mt-auto">
              <Footer />
            </div>
          </Provider>
        </body>
      </html>
    
  );
}
